### ISSUE TITLE
'True' und 'False' sind als Synonyme in der NLU hinterlegt

### ISSUE THREAD

**Issue by noopliez** [Schlaue-Lise-IT-Project/schlaue-lise#77]
So wie der Stand aktuell ist funktioniert er zwar, es stimmt aber einfach von der **Semantik** her nicht. 

Folgendes ist das Problem:

```yaml
# nlu_medicine.yml

version: "2.0"
nlu:
- intent: medicine_specific_insurancestatus
  examples: |
    - bin [versichert]{"entity": "insurancestatus", "value": "True"}
    - bin [nicht versichert]{"entity": "insurancestatus", "value": "False"}
    - [versichert]{"entity": "insurancestatus", "value": "True"}
    - [nicht versichert]{"entity": "insurancestatus", "value": "False"}
    - habe eine [Versicherung]{"entity": "insurancestatus", "value": "True"}
    - habe [keine Versicherung]{"entity": "insurancestatus", "value": "False"}
    - [Versicherung]{"entity": "insurancestatus", "value": "True"}
    - [keine Versicherung]{"entity": "insurancestatus", "value": "False"}
    - ich bin [versichert]{"entity": "insurancestatus", "value": "True"}
```

Wie man hier sieht, werden als values `True/False` angegeben. Soweit anscheinend in Ordnung. Das Problem ist, dass hier keine _richtigen_ Booleans erschaffen werden, sondern die zwei Werte von Rasa als Synonyme verwendet werden, wie man hier sieht:

```yaml
# nlu_medicine.yml

- synonym: 'False'
  examples: |
    - nicht versichert
    - keine Versicherung

```

Das ganze funktioniert, ist aber meiner Meinung nach einfach falsch. Ich bin mir ziemlich sicher, dass man in der `NLU` keine Booleans setzen kann, sondern ausschließlich in einer `Form`. Versucht man es über die `NLU` erzeugt Rasa automatisch diese Synonyme. 

Ich hätte hier gerne eine Diskussion dazu.

**Comment by noopliez** [comment]
Bis zum Vortrag am Donnerstag muss das nicht gemacht werden, aber ich will das nicht so in der finalen Abgabe haben.

**Comment by Pusteblum3** [comment]
Vielleicht als "Info"-/"Anhaltspunkt" für die Diskussion später/irgendwann. Orientiert hatte ich mich für medizin an der nlu_schlafen.yml: 

`- intent: inform
    examples: |
      - Ich bin [18](alter) Jahre alt
      - Ich bin [17](alter)
      - Ich bin [52](alter) Jahre
      - Ich bin unter [18](alter)
      - Ich bin älter als [18](alter)
      - [18](alter)
      - [32](alter)
      - Ich bin [männlich](geschlecht)
      - Ich bin ein [Mann]{"entity": "geschlecht", "value": "männlich"}
      - [Mann]{"entity": "geschlecht", "value": "männlich"}
      - Ein [Mann]{"entity": "geschlecht", "value": "männlich"}
      - Ein [Junge]{"entity": "geschlecht", "value": "männlich"}
      - [Junge]{"entity": "geschlecht", "value": "männlich"}
      - Ich bin [weiblich](geschlecht)
      - Ich bin eine [Frau]{"entity": "geschlecht", "value": "weiblich"}
      - [Frau]{"entity": "geschlecht", "value": "weiblich"}
      - Eine [Frau]{"entity": "geschlecht", "value": "weiblich"}
      - ... `

**Comment by noopliez** [comment]
Ja genau, da werden die Entities mit den `{}`-Klammern gesetzt. Das funktioniert aber meines Wissens mit Booleans nicht. Ein Beispiel wie in 'Schlafen' (bzw. den Vorinformationen dazu) die Booleans gesetzt werden ist folgendes:

```yaml
forms:
  informationen_form:
    required_slots:
      alter:
      - entity: alter
        intent: inform
        type: from_entity
      bgeschlecht:
      - entity: bgeschlecht
        intent: inform
        type: from_entity
      - intent: deny
        type: from_intent
        value: divers
      chaustierhalter:
      - intent: affirm
        type: from_intent
        value: true
      - intent: deny
        type: from_intent
        value: false
      - intent: inform
        type: from_intent
        value: None
      drogenabhaengig:
      - intent: affirm
        type: from_intent
        value: true
      - intent: deny
        type: from_intent
        value: false
      - intent: inform
        type: from_intent
        value: None
```

Ob das auch so für 'Medizin' umgesetzt werden kann, weiß ich aktuell nicht. So hat es aber glaube ich auch die @Lena-Holderrieth für 'Spenden' umgesetzt.
